export const prefetchAdminBundle = () => {
  import("../pages/admin/AdminDashboard")
  import("../pages/admin/AdminUsers")
  import("../pages/admin/AdminUserDetails")
  import("../pages/admin/AdminClasses")
  import("../pages/admin/AdminClassDetails")
  import("../pages/admin/AdminSettings")
  import("../pages/admin/AdminAssignmentGroups")
  import("../pages/admin/AdminCreateAssignmentGroup")
  import("../pages/admin/AdminEditAssignmentGroup")
  import("../pages/admin/AdminAssignmentGroupDetails")
  import("../pages/admin/AdminAssignmentGroupDetailsSubmit")
  import("../pages/admin/AdminArchiveAssignmentGroups")
  import("../pages/admin/AdminArchiveAssignmentGroupDetails")
  import("../pages/admin/AdminAGTemplates")
  import("../pages/admin/AdminCreateAGTemplate")
  import("../pages/admin/AdminEditAGTemplate")
  import("../pages/admin/AdminGns3")
  import("../pages/admin/AdminGnsAllSessions")
}

export const prefetchTeacherBundle = () => {
  import("../pages/teacher/TeacherDashboard")
  import("../pages/teacher/TeacherMyClasses")
  import("../pages/teacher/TeacherStudentDetails")
  import("../pages/teacher/TeacherClassDetails")
  import("../pages/teacher/TeacherAssignmentGroups")
  import("../pages/teacher/TeacherCreateAssignmentGroup")
  import("../pages/teacher/TeacherEditAssignmentGroup")
  import("../pages/teacher/TeacherAssignmentGroupDetails")
  import("../pages/teacher/TeacherAssignmentGroupDetailsSubmit")
  import("../pages/teacher/TeacherArchiveAssignmentGroups")
  import("../pages/teacher/TeacherArchiveAssignmentGroupDetails")
  import("../pages/teacher/TeacherAGTemplates")
  import("../pages/teacher/TeacherCreateAGTemplate")
  import("../pages/teacher/TeacherEditAGTemplate")
  import("../pages/teacher/TeacherGns3")
  import("../pages/teacher/TeacherGns3AllSessions")
}

export const prefetchStudentBundle = () => {
  import("../pages/student/StudentDashboard")
  import("../pages/student/StudentAssignments")
  import("../pages/student/StudentAssignmentSubmission")
  import("../pages/student/StudentAssignmentDetails")
  import("../pages/student/StudentGns3")
  import("../pages/student/StudentArchiveAssignmentGroups")
}