export enum RouteParams {
  ASSIGNMENT_GROUP_ID = "ASSIGNMENT_GROUP_ID",
  ASSIGNMENT_GROUP_TYPE = "ASSIGNMENT_TYPE",
  ASSIGNMENT_ID = "ASSIGNMENT_ID",
  STUDENT_ID = "STUDENT_ID",
  CLASS_ID = "CLASS_ID",
  USER_ID = "USER_ID",
  TEMPLATE_ID = "TEMPLATE_ID",
}

export enum RouteKeys {
  LOGIN,

  ADMIN,
  ADMIN_DASHBOARD,
  ADMIN_USERS,
  ADMIN_USER_DETAILS,
  ADMIN_CLASSES,
  ADMIN_CLASS_DETAILS,
  ADMIN_GNS3,
  ADMIN_GNS3_ALL_SESSIONS,
  ADMIN_SETTINGS,
  ADMIN_ASSIGNMENT_GROUPS,
  ADMIN_ASSIGNMENT_GROUPS_CREATE,
  ADMIN_ASSIGNMENT_GROUPS_EDIT,
  ADMIN_ASSIGNMENT_GROUPS_DETAILS,
  ADMIN_ASSIGNMENT_GROUPS_DETAILS_SUBMIT,
  ADMIN_ASSIGNMENT_GROUPS_ARCHIVE,
  ADMIN_AG_TEMPLATES,
  ADMIN_AG_TEMPLATE_CREATE,
  ADMIN_AG_TEMPLATE_EDIT,

  TEACHER,
  TEACHER_DASHBOARD,
  TEACHER_MY_CLASSES,
  TEACHER_MY_CLASSES_STUDENT_DETAILS,
  TEACHER_MY_CLASSES_CLASS_DETAILS,
  TEACHER_ASSIGNMENT_GROUPS,
  TEACHER_ASSIGNMENT_GROUPS_CREATE,
  TEACHER_ASSIGNMENT_GROUPS_EDIT,
  TEACHER_ASSIGNMENT_GROUPS_DETAILS,
  TEACHER_ASSIGNMENT_GROUPS_DETAILS_SUBMIT,
  TEACHER_ASSIGNMENT_GROUPS_ARCHIVE,
  TEACHER_AG_TEMPLATES,
  TEACHER_AG_TEMPLATE_CREATE,
  TEACHER_AG_TEMPLATE_EDIT,
  TEACHER_GNS3,
  TEACHER_GNS3_ALL_SESSIONS,

  STUDENT,
  STUDENT_DASHBOARD,
  STUDENT_ASSIGNMENTS,
  STUDENT_ASSIGNMENT_SUBMISSION,
  STUDENT_ASSIGNMENT_DETAILS,
  STUDENT_ASSIGNMENT_GROUPS_ARCHIVE,
  STUDENT_GNS3,
}

const LOGIN = "/login"

const ADMIN = "/admin"
const ADMIN_DASHBOARD = `${ADMIN}/dashboard`
const ADMIN_USERS = `${ADMIN}/users`
const ADMIN_USER_DETAILS = `${ADMIN_USERS}/details/:${RouteParams.USER_ID}`
const ADMIN_CLASSES = `${ADMIN}/classes`
const ADMIN_CLASS_DETAILS = `${ADMIN_CLASSES}/details/:${RouteParams.CLASS_ID}`
const ADMIN_GNS3 = `${ADMIN}/gns3`
const ADMIN_GNS3_ALL_SESSIONS = `${ADMIN_GNS3}/all-sessions`
const ADMIN_SETTINGS = `${ADMIN}/settings`
const ADMIN_ASSIGNMENT_GROUPS = `${ADMIN}/assignment-groups`
const ADMIN_ASSIGNMENT_GROUPS_CREATE = `${ADMIN_ASSIGNMENT_GROUPS}/create`
const ADMIN_ASSIGNMENT_GROUPS_EDIT = `${ADMIN_ASSIGNMENT_GROUPS}/:${RouteParams.ASSIGNMENT_GROUP_TYPE}/edit/:${RouteParams.ASSIGNMENT_GROUP_ID}`
const ADMIN_ASSIGNMENT_GROUPS_DETAILS = `${ADMIN_ASSIGNMENT_GROUPS}/:${RouteParams.ASSIGNMENT_GROUP_TYPE}/details/:${RouteParams.ASSIGNMENT_GROUP_ID}`
const ADMIN_ASSIGNMENT_GROUPS_DETAILS_SUBMIT = `${ADMIN_ASSIGNMENT_GROUPS_DETAILS}/:${RouteParams.ASSIGNMENT_ID}`
const ADMIN_ASSIGNMENT_GROUPS_ARCHIVE = `${ADMIN_ASSIGNMENT_GROUPS}/archive`
const ADMIN_AG_TEMPLATES = `${ADMIN_ASSIGNMENT_GROUPS}/templates`
const ADMIN_AG_TEMPLATE_CREATE = `${ADMIN_AG_TEMPLATES}/create`
const ADMIN_AG_TEMPLATE_EDIT = `${ADMIN_AG_TEMPLATES}/edit/:${RouteParams.TEMPLATE_ID}`

const TEACHER = "/teacher"
const TEACHER_DASHBOARD = `${TEACHER}/dashboard`
const TEACHER_MY_CLASSES = `${TEACHER}/my-classes`
const TEACHER_MY_CLASSES_STUDENT_DETAILS = `${TEACHER_MY_CLASSES}/student-details/:${RouteParams.STUDENT_ID}`
const TEACHER_MY_CLASSES_CLASS_DETAILS = `${TEACHER_MY_CLASSES}/class-details/:${RouteParams.CLASS_ID}`
const TEACHER_ASSIGNMENT_GROUPS = `${TEACHER}/assignment-groups`
const TEACHER_ASSIGNMENT_GROUPS_CREATE = `${TEACHER_ASSIGNMENT_GROUPS}/create`
const TEACHER_ASSIGNMENT_GROUPS_EDIT = `${TEACHER_ASSIGNMENT_GROUPS}/:${RouteParams.ASSIGNMENT_GROUP_TYPE}/edit/:${RouteParams.ASSIGNMENT_GROUP_ID}`
const TEACHER_ASSIGNMENT_GROUPS_DETAILS = `${TEACHER_ASSIGNMENT_GROUPS}/:${RouteParams.ASSIGNMENT_GROUP_TYPE}/details/:${RouteParams.ASSIGNMENT_GROUP_ID}`
const TEACHER_ASSIGNMENT_GROUPS_DETAILS_SUBMIT = `${TEACHER_ASSIGNMENT_GROUPS_DETAILS}/:${RouteParams.ASSIGNMENT_ID}`
const TEACHER_ASSIGNMENT_GROUPS_ARCHIVE = `${TEACHER_ASSIGNMENT_GROUPS}/archive`
const TEACHER_AG_TEMPLATES = `${TEACHER_ASSIGNMENT_GROUPS}/templates`
const TEACHER_AG_TEMPLATE_CREATE = `${TEACHER_AG_TEMPLATES}/create`
const TEACHER_AG_TEMPLATE_EDIT = `${TEACHER_AG_TEMPLATES}/edit/:${RouteParams.TEMPLATE_ID}`
const TEACHER_GNS3 = `${TEACHER}/gns3`
const TEACHER_GNS3_ALL_SESSIONS = `${TEACHER_GNS3}/all-sessions`

const STUDENT = "/student"
const STUDENT_DASHBOARD = `${STUDENT}/dashboard`
const STUDENT_ASSIGNMENS = `${STUDENT}/assignments`
const STUDENT_ASSIGNMENT_SUBMISSION = `${STUDENT_ASSIGNMENS}/:${RouteParams.ASSIGNMENT_GROUP_TYPE}/submit/:${RouteParams.ASSIGNMENT_ID}`
const STUDENT_ASSIGNMENT_DETAILS = `${STUDENT_ASSIGNMENS}/:${RouteParams.ASSIGNMENT_GROUP_TYPE}/details/:${RouteParams.ASSIGNMENT_ID}`
const STUDENT_ASSIGNMENT_GROUPS_ARCHIVE = `${STUDENT_ASSIGNMENS}/archive`
const STUDENT_GNS3 = `${STUDENT}/gns3`

/**
 * Generates a URL with parameters replaced with a provided values.
 */
export const getParametrizedUrl = (route: RouteKeys, params: { [key in RouteParams]?: string }) => {
  let _route = Routes[route]
  for (const [key, value] of Object.entries(params)) {
    _route = _route.replace(`:${key}`, value)
  }
  return _route
}

export const Routes: Record<RouteKeys, string> = {
  [RouteKeys.LOGIN]: LOGIN,

  [RouteKeys.ADMIN]: ADMIN,
  [RouteKeys.ADMIN_DASHBOARD]: ADMIN_DASHBOARD,
  [RouteKeys.ADMIN_USERS]: ADMIN_USERS,
  [RouteKeys.ADMIN_USER_DETAILS]: ADMIN_USER_DETAILS,
  [RouteKeys.ADMIN_CLASSES]: ADMIN_CLASSES,
  [RouteKeys.ADMIN_CLASS_DETAILS]: ADMIN_CLASS_DETAILS,
  [RouteKeys.ADMIN_GNS3]: ADMIN_GNS3,
  [RouteKeys.ADMIN_GNS3_ALL_SESSIONS]: ADMIN_GNS3_ALL_SESSIONS,
  [RouteKeys.ADMIN_SETTINGS]: ADMIN_SETTINGS,
  [RouteKeys.ADMIN_ASSIGNMENT_GROUPS]: ADMIN_ASSIGNMENT_GROUPS,
  [RouteKeys.ADMIN_ASSIGNMENT_GROUPS_CREATE]: ADMIN_ASSIGNMENT_GROUPS_CREATE,
  [RouteKeys.ADMIN_ASSIGNMENT_GROUPS_EDIT]: ADMIN_ASSIGNMENT_GROUPS_EDIT,
  [RouteKeys.ADMIN_ASSIGNMENT_GROUPS_DETAILS]: ADMIN_ASSIGNMENT_GROUPS_DETAILS,
  [RouteKeys.ADMIN_ASSIGNMENT_GROUPS_DETAILS_SUBMIT]: ADMIN_ASSIGNMENT_GROUPS_DETAILS_SUBMIT,
  [RouteKeys.ADMIN_ASSIGNMENT_GROUPS_ARCHIVE]: ADMIN_ASSIGNMENT_GROUPS_ARCHIVE,
  [RouteKeys.ADMIN_AG_TEMPLATES]: ADMIN_AG_TEMPLATES,
  [RouteKeys.ADMIN_AG_TEMPLATE_CREATE]: ADMIN_AG_TEMPLATE_CREATE,
  [RouteKeys.ADMIN_AG_TEMPLATE_EDIT]: ADMIN_AG_TEMPLATE_EDIT,

  [RouteKeys.TEACHER]: TEACHER,
  [RouteKeys.TEACHER_DASHBOARD]: TEACHER_DASHBOARD,
  [RouteKeys.TEACHER_MY_CLASSES]: TEACHER_MY_CLASSES,
  [RouteKeys.TEACHER_MY_CLASSES_STUDENT_DETAILS]: TEACHER_MY_CLASSES_STUDENT_DETAILS,
  [RouteKeys.TEACHER_MY_CLASSES_CLASS_DETAILS]: TEACHER_MY_CLASSES_CLASS_DETAILS,
  [RouteKeys.TEACHER_ASSIGNMENT_GROUPS]: TEACHER_ASSIGNMENT_GROUPS,
  [RouteKeys.TEACHER_ASSIGNMENT_GROUPS_CREATE]: TEACHER_ASSIGNMENT_GROUPS_CREATE,
  [RouteKeys.TEACHER_ASSIGNMENT_GROUPS_EDIT]: TEACHER_ASSIGNMENT_GROUPS_EDIT,
  [RouteKeys.TEACHER_ASSIGNMENT_GROUPS_DETAILS]: TEACHER_ASSIGNMENT_GROUPS_DETAILS,
  [RouteKeys.TEACHER_ASSIGNMENT_GROUPS_DETAILS_SUBMIT]: TEACHER_ASSIGNMENT_GROUPS_DETAILS_SUBMIT,
  [RouteKeys.TEACHER_ASSIGNMENT_GROUPS_ARCHIVE]: TEACHER_ASSIGNMENT_GROUPS_ARCHIVE,
  [RouteKeys.TEACHER_AG_TEMPLATES]: TEACHER_AG_TEMPLATES,
  [RouteKeys.TEACHER_AG_TEMPLATE_CREATE]: TEACHER_AG_TEMPLATE_CREATE,
  [RouteKeys.TEACHER_AG_TEMPLATE_EDIT]: TEACHER_AG_TEMPLATE_EDIT,
  [RouteKeys.TEACHER_GNS3]: TEACHER_GNS3,
  [RouteKeys.TEACHER_GNS3_ALL_SESSIONS]: TEACHER_GNS3_ALL_SESSIONS,

  [RouteKeys.STUDENT]: STUDENT,
  [RouteKeys.STUDENT_DASHBOARD]: STUDENT_DASHBOARD,
  [RouteKeys.STUDENT_ASSIGNMENTS]: STUDENT_ASSIGNMENS,
  [RouteKeys.STUDENT_ASSIGNMENT_SUBMISSION]: STUDENT_ASSIGNMENT_SUBMISSION,
  [RouteKeys.STUDENT_ASSIGNMENT_DETAILS]: STUDENT_ASSIGNMENT_DETAILS,
  [RouteKeys.STUDENT_ASSIGNMENT_GROUPS_ARCHIVE]: STUDENT_ASSIGNMENT_GROUPS_ARCHIVE,
  [RouteKeys.STUDENT_GNS3]: STUDENT_GNS3,
}