export enum RouteParams {
  ASSIGNMENT_GROUP_ID = "ASSIGNMENT_GROUP_ID",
  ASSIGNMENT_GROUP_TYPE = "ASSIGNMENT_TYPE",
  ASSIGNMENT_ID = "ASSIGNMENT_ID",
  STUDENT_ID = "STUDENT_ID",
  CLASS_ID = "CLASS_ID",
  USER_ID = "USER_ID",
}

export enum RouteKeys {
  LOGIN,

  ADMIN,
  ADMIN_DASHBOARD,
  ADMIN_USERS,
  ADMIN_USER_DETAILS,
  ADMIN_CLASSES,
  ADMIN_CLASS_DETAILS,
  ADMIN_GNS3,
  ADMIN_SETTINGS,

  TEACHER,
  TEACHER_DASHBOARD,
  TEACHER_MY_CLASSES,
  TEACHER_MY_CLASSES_STUDENT_DETAILS,
  TEACHER_MY_CLASSES_CLASS_DETAILS,
  TEACHER_ASSIGNMENT_GROUPS,
  TEACHER_ASSIGNMENT_GROUPS_DETAILS,
  TEACHER_ASSIGNMENT_GROUPS_DETAILS_SUBMIT,
  TEACHER_GNS3,

  STUDENT,
  STUDENT_DASHBOARD,
  STUDENT_ASSIGNMENTS,
  STUDENT_ASSIGNMENT_SUBMISSION,
  STUDENT_ASSIGNMENT_DETAILS,
  STUDENT_GNS3,
}

const LOGIN = "/login"

const ADMIN = "/admin"
const ADMIN_DASHBOARD = `${ADMIN}/dashboard`
const ADMIN_USERS = `${ADMIN}/users`
const ADMIN_USER_DETAILS = `${ADMIN_USERS}/details/:${RouteParams.USER_ID}`
const ADMIN_CLASSES = `${ADMIN}/classes`
const ADMIN_CLASS_DETAILS = `${ADMIN_CLASSES}/details/:${RouteParams.CLASS_ID}`
const ADMIN_GNS3 = `${ADMIN}/gns3`
const ADMIN_SETTINGS = `${ADMIN}/settings`

const TEACHER = "/teacher"
const TEACHER_DASHBOARD = `${TEACHER}/dashboard`
const TEACHER_MY_CLASSES = `${TEACHER}/my-classes`
const TEACHER_MY_CLASSES_STUDENT_DETAILS = `${TEACHER_MY_CLASSES}/student-details/:${RouteParams.STUDENT_ID}`
const TEACHER_MY_CLASSES_CLASS_DETAILS = `${TEACHER_MY_CLASSES}/class-details/:${RouteParams.CLASS_ID}`
const TEACHER_ASSIGNMENT_GROUPS = `${TEACHER}/assignment-groups`
const TEACHER_ASSIGNMENT_GROUPS_DETAILS = `${TEACHER_ASSIGNMENT_GROUPS}/:${RouteParams.ASSIGNMENT_GROUP_TYPE}/details/:${RouteParams.ASSIGNMENT_GROUP_ID}`
const TEACHER_ASSIGNMENT_GROUPS_DETAILS_SUBMIT = `${TEACHER_ASSIGNMENT_GROUPS_DETAILS}/:${RouteParams.ASSIGNMENT_ID}`
const TEACHER_GNS3 = `${TEACHER}/gns3`

const STUDENT = "/student"
const STUDENT_DASHBOARD = `${STUDENT}/dashboard`
const STUDENT_ASSIGNMENS = `${STUDENT}/assignments`
const STUDENT_ASSIGNMENT_SUBMISSION = `${STUDENT_ASSIGNMENS}/:${RouteParams.ASSIGNMENT_GROUP_TYPE}/submit/:${RouteParams.ASSIGNMENT_ID}`
const STUDENT_ASSIGNMENT_DETAILS = `${STUDENT_ASSIGNMENS}/:${RouteParams.ASSIGNMENT_GROUP_TYPE}/details/:${RouteParams.ASSIGNMENT_ID}`
const STUDENT_GNS3 = `${STUDENT}/gns3`

/**
 * Generates a URL with parameters replaced with a provided values.
 */
export const getParametrizedUrl = (route: RouteKeys, params: { [key in RouteParams]?: string }) => {
  let _route = Routes[route]
  for (const [key, value] of Object.entries(params)) {
    _route = _route.replace(`:${key}`, value)
  }
  return _route
}

export const Routes: Record<RouteKeys, string> = {
  [RouteKeys.LOGIN]: LOGIN,

  [RouteKeys.ADMIN]: ADMIN,
  [RouteKeys.ADMIN_DASHBOARD]: ADMIN_DASHBOARD,
  [RouteKeys.ADMIN_USERS]: ADMIN_USERS,
  [RouteKeys.ADMIN_USER_DETAILS]: ADMIN_USER_DETAILS,
  [RouteKeys.ADMIN_CLASSES]: ADMIN_CLASSES,
  [RouteKeys.ADMIN_CLASS_DETAILS]: ADMIN_CLASS_DETAILS,
  [RouteKeys.ADMIN_GNS3]: ADMIN_GNS3,
  [RouteKeys.ADMIN_SETTINGS]: ADMIN_SETTINGS,

  [RouteKeys.TEACHER]: TEACHER,
  [RouteKeys.TEACHER_DASHBOARD]: TEACHER_DASHBOARD,
  [RouteKeys.TEACHER_MY_CLASSES]: TEACHER_MY_CLASSES,
  [RouteKeys.TEACHER_MY_CLASSES_STUDENT_DETAILS]: TEACHER_MY_CLASSES_STUDENT_DETAILS,
  [RouteKeys.TEACHER_MY_CLASSES_CLASS_DETAILS]: TEACHER_MY_CLASSES_CLASS_DETAILS,
  [RouteKeys.TEACHER_ASSIGNMENT_GROUPS]: TEACHER_ASSIGNMENT_GROUPS,
  [RouteKeys.TEACHER_ASSIGNMENT_GROUPS_DETAILS]: TEACHER_ASSIGNMENT_GROUPS_DETAILS,
  [RouteKeys.TEACHER_ASSIGNMENT_GROUPS_DETAILS_SUBMIT]: TEACHER_ASSIGNMENT_GROUPS_DETAILS_SUBMIT,
  [RouteKeys.TEACHER_GNS3]: TEACHER_GNS3,

  [RouteKeys.STUDENT]: STUDENT,
  [RouteKeys.STUDENT_DASHBOARD]: STUDENT_DASHBOARD,
  [RouteKeys.STUDENT_ASSIGNMENTS]: STUDENT_ASSIGNMENS,
  [RouteKeys.STUDENT_ASSIGNMENT_SUBMISSION]: STUDENT_ASSIGNMENT_SUBMISSION,
  [RouteKeys.STUDENT_ASSIGNMENT_DETAILS]: STUDENT_ASSIGNMENT_DETAILS,
  [RouteKeys.STUDENT_GNS3]: STUDENT_GNS3,
}